name: Build Docker Rewards - Debian

on:
  # 1. Gatilho para execuÃ§Ã£o manual a partir da aba "Actions"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ³ Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ğŸ”§ Build da imagem
        run: docker build -f DockerfileDebian -t ${{ secrets.DOCKER_USERNAME }}/python:latest .

      - name: ğŸš€ Push para o Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python:latest
